[package]
name = "update-attributes-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.update-attributes]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.52.3"
default-features = false
